name: Setup OpenVic Environment
description: Setup OpenVic Environment
runs:
  using: "composite"
  steps:
    - name: Setup URL Environment
      shell: bash
      run: ${GITHUB_ACTION_PATH}/url-environment.sh

    - name: Setup Commit Environment
      uses: actions/github-script@v6
      with:
        script: require(`${process.env.GITHUB_ACTION_PATH}/commit-environment.js`)({github, context, core})
